# Generated by Django 6.0.6 on 2026-07-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_waypoints', models.JSONField(default=list, help_text="List of waypoints in order: [{'type': 'pickup'|'delivery', 'lat': 0, 'lng': 0, 'name': ''}]")),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='planned', max_length=20)),
                ('briefing_text', models.TextField(blank=True, help_text='AI-generated dispatch briefing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(blank=True, limit_choices_to={'role': 'dispatcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(related_name='routes', to='matching.match')),
            ],
        ),
    ]
