# Generated by Django 6.0.6 on 2026-07-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='farmers.collectionpoint')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='farmers.croptype')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('crop_type', 'collection_point', 'date')},
            },
        ),
    ]
