# Generated by Django 6.0.6 on 2026-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buyerprofile_latitude_buyerprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=500000.0, help_text='Demo wallet balance in Naira (₦)', max_digits=14),
        ),
    ]
