# Generated by Django 6.0.6 on 2026-07-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('has_cold_storage', models.BooleanField(default=False)),
                ('solar_powered', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('typical_shelf_life_days', models.PositiveIntegerField(default=7)),
                ('perishability_score', models.PositiveSmallIntegerField(default=5, help_text='1 (least) to 10 (most perishable)')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Grading'), ('graded', 'Graded'), ('matched', 'Matched to Buyer'), ('sold', 'Sold'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Below Standard)'), ('rejected', 'Rejected'), ('ungraded', 'Not Yet Graded')], default='ungraded', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produce/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='farmers.collectionpoint')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='farmers.croptype')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
