# Generated by Django 6.0.6 on 2026-07-22 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('estimated_shelf_days', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, help_text='Full Gemma response for debugging')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_result', to='farmers.producelisting')),
            ],
        ),
    ]
