# Generated by Django 6.0.6 on 2026-07-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_grade', models.CharField(choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Below Standard)'), ('rejected', 'Rejected'), ('ungraded', 'Not Yet Graded')], default='B', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='farmers.croptype')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending_delivery', 'Pending Delivery'), ('delivered', 'Delivered')], default='pending_delivery', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='farmers.producelisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matching.buyerorder')),
            ],
        ),
    ]
