# Generated by Django 6.0.6 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_for_payment', 'Waiting for Payment'), ('processing', 'Processing'), ('delivery_in_process', 'Delivery in Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
